apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - deployment.yml

secretGenerator:
  - name: cloudflared-token
    namespace: cloudflare-tunnel-shared
    env: ../../../../secrets/cloudflare-tunnel-shared.env
