apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - net/traefik-config
  - net/cloudflare-tunnel-shared
  - net/cloudflare-tunnel-jp # TODO: use overlays
  - monitor/grafana-k8s-monitoring
  - db/postgresql-operator
  # - db/consul
