all:
  children:
    k3s_cluster:
      vars:
        region: ap-northeast-1
        timezone: Asia/Tokyo
      children:
        server:
          hosts:
            p-home-sapporo:
              ansible_host: 100.64.0.0
              node_id: jp-01
        # agent:
        #   hosts:
