services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    restart: always
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      # - "--path.rootfs=/rootfs"
    ports:
      - 9100:9100
    networks:
      - external_network
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      # - /:/rootfs:ro,rslave

  cadvisor:
    image: ghcr.io/google/cadvisor
    restart: always
    ports:
      - 8080:8080
    networks:
      - external_network
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      # - /:/rootfs:ro,rslave
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      # - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

networks:
  external_network:
    external: true
