global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'senates_node'
    static_configs:
      - targets: ['tokyo:9100']
        labels:
          group: 'senates'

  - job_name: 'senates_container'
    static_configs:
      - targets: ['tokyo:8000']
        labels:
          group: 'senates'

  - job_name: 'workers-node'
    static_configs:
      - targets: ['sapporo:9100']
        labels:
          group: 'workers'

  - job_name: 'workers-container'
    static_configs:
      - targets: ['sapporo:8000']
        labels:
          group: 'workers'
