apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/common/reflector
  - infra/net/traefik-config
  - infra/net/cloudflare-tunnel-shared
  - infra/net/cloudflare-tunnel-jp # TODO: use overlays
  - infra/monitor/grafana-k8s-monitoring
  - infra/db/postgresql-operator
  # - infra/db/consul

  - apps/misskey/mk-dev.xiupos.net
  - apps/misskey/mk.xiupos.net
